### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mcst12345** [ConnorTron110/SCP-Lockdown-Issues#32] opened 2022-07-26 01:27 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  miku (miku-1.0.1-pre11.jar)
  LoliPickaxeCore (LoliPickaxe-1.2.12-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/26/22 9:14 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at alexiy.secure.contain.protect.events.CommonEvents.onEntityUpdate(CommonEvents.java:212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_CommonEvents_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.anotherstar.core.util.EventUtil.onLivingUpdate(EventUtil.java:91)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at alexiy.secure.contain.protect.events.CommonEvents.onEntityUpdate(CommonEvents.java:212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_CommonEvents_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.anotherstar.core.util.EventUtil.onLivingUpdate(EventUtil.java:91)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: miku:hatsune_miku (miku.Entity.Hatsune_Miku)
	Entity ID: 34
	Entity Name: 初音未来
	Entity's Exact location: 1605.50, 1.00, -533.50
	Entity's Block location: World: (1605,1,-534), Chunk: (at 5,0,10 in 100,-34; contains blocks 1600,0,-544 to 1615,255,-529), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: test的副本
	All players: 1 total; [EntityPlayerMP['mcst12345'/0, l='test的副本', x=1606.11, y=1.00, z=-534.63]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: -7204007182760379827
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock;1;village
	Level spawn location: World: (1607,4,-532), Chunk: (at 7,0,12 in 100,-34; contains blocks 1600,0,-544 to 1615,255,-529), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
	Level time: 1039 game time, 1039 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 173446 (now: false), thunder time: 44545 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.15.0-41-generic
	Java Version: 1.8.0_312, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 2011044480 bytes (1917 MB) / 4194304000 bytes (4000 MB) up to 4194304000 bytes (4000 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx4000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G6_pre1 16 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version             | Source                                                    | Signature                                |
	|:------ |:--------------- |:------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2              | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp             | 9.42                | minecraft.jar                                             | None                                     |
	| LCHIJA | FML             | 8.0.99.99           | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2860        | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | aoa3            | 3.3.6               | AoA3-3.3.6.jar                                            | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | darknesslib     | 1.1.2               | DarknessLib-1.12.2-1.1.2.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | grue            | 1.8.1               | Grue-1.12.2-1.8.1.jar                                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | jei             | 4.16.1.302          | jei_1.12.2-4.16.1.302.jar                                 | None                                     |
	| LCHIJA | lolipickaxe     | 1.2.12              | LoliPickaxe-1.2.12-1.12.2.jar                             | None                                     |
	| LCHIJA | lycanitesmobs   | 2.0.8.5 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.8.5.jar                          | None                                     |
	| LCHIJA | manaita_plus    | 1.0.1               | Manaita+Plus-1.12.2-1.0.1.jar                             | None                                     |
	| LCHIJA | miku            | 1.0.1-pre11         | miku-1.0.1-pre11.jar                                      | None                                     |
	| LCHIJA | mobbattle       | 2.3.4               | MobBattleMod-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJA | scp             | $$version           | SCP_Lockdown-1.12.2-2.4.1-release.jar                     | None                                     |
	| LCHIJA | huajiage        | 1.3.6.2-release     | 【滑稽纪元Ⅱ】HuajiAge-InfiniteGalaxy-1.12.2-1.3.6.2-release.jar | None                                     |
	| UD     | lolipickaxecore | 1.2.12              | minecraft.jar                                             | None                                     |

	Loaded coremods (and transformers): 
miku (miku-1.0.1-pre11.jar)
  miku.Core.ClassTransformer
LoliPickaxeCore (LoliPickaxe-1.2.12-1.12.2.jar)
  com.anotherstar.core.transformer.LoliPickaxeTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['mcst12345'/0, l='test的副本', x=1606.11, y=1.00, z=-534.63]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1 Mesa 22.0.1
	OpenGlRenderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ConnorTron110** [comment] 2022-07-30 18:59
It seems to be related to the `Hatsune_Miku` Entity and no capability being attached, there is a check to see if it has it but this should not cause an issue. I will take a further look into this.

**Comment by ConnorTron110** [comment] 2022-08-16 02:14
I've marked this issue as unreproducible as I'm unable to look at the mod that caused the problem, I searched for it on curse forge with no results. If you can point me to the mod in question that would be great, but if it does not come from Curseforge, I will not attempt to fix it.

For now, I will close this issue. I will reopen once I find the mod that causes the issue.

**Closed by ConnorTron110** 2022-08-16 02:14 UTC
Labels: Bug, 1.12, Unreproducable
